name: Generate Repo Structure

on:
  push:
    branches:
      - main

permissions:
  contents: write  

jobs:
  generate-structure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate repo structure JSON
        run: |
          echo '{' > repo-structure.json
          echo '  "repo": "'$(basename $GITHUB_REPOSITORY)'",' >> repo-structure.json
          echo '  "structure": {' >> repo-structure.json
          find . -type d ! -path '*/\.*' | while read -r dir; do
            files=$(find "$dir" -maxdepth 1 -type f ! -path '*/\.*' -exec basename {} \; | jq -R . | jq -s .)
            echo '    "'"$dir"'": '"$files"','
          done | sed '$ s/,$//' >> repo-structure.json
          echo '  }' >> repo-structure.json
          echo '}' >> repo-structure.json

      - name: Overwrite README.md with JSON
        run: |
          cat repo-structure.json | jq . > README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update repo structure in README.md" || echo "No changes to commit"
          git push origin HEAD:main
