name: Generate Repo Structure

on:
  push:
    branches:
      - main

permissions:
  contents: write   # allow push to repo

jobs:
  generate-structure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq yq

      - name: Generate repo structure JSON
        run: |
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          echo '{ "repo": "'"$REPO_NAME"'", "structure": {' > repo-structure.json
          > tmp.json

          # Iterate through folders
          find . -type d ! -path '*/\.*' | while read -r dir; do
            echo '    "'"$dir"'": {' >> tmp.json

            # Process each file in that folder
            find "$dir" -maxdepth 1 -type f ! -path '*/\.*' | while read -r file; do
              filename=$(basename "$file")
              if [[ $filename == *.md ]]; then
                # Extract YAML front matter (between --- ... ---)
                FRONTMATTER=$(awk '/^---/{flag=!flag; next} flag' "$file")
                if [ -n "$FRONTMATTER" ]; then
                  # Parse with yq (fail action if invalid YAML)
                  META=$(echo "$FRONTMATTER" | yq -o=json '.')
                  echo '      "'"$filename"'": '"$META"',' >> tmp.json
                else
                  echo '      "'"$filename"'": {} ,' >> tmp.json
                fi
              else
                echo '      "'"$filename"'": {} ,' >> tmp.json
              fi
            done

            # close folder JSON
            sed -i '$ s/,$//' tmp.json
            echo '    },' >> tmp.json
          done

          # Clean trailing commas and close JSON
          sed -i '$ s/,$//' tmp.json
          cat tmp.json >> repo-structure.json
          echo '  } }' >> repo-structure.json
          rm tmp.json

      - name: Overwrite README.md with JSON
        run: |
          cat repo-structure.json | jq . > README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update repo structure in README.md" || echo "No changes to commit"
          git push origin HEAD:main
